name: Manual Publish to GitHub Packages

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  publish:
    uses: MCEngine-Action/gradle/.github/workflows/publish-gradle-with-testing.yml@master
    with:
      repo-name: ${{ github.repository }}
    secrets:
      USER_GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
